FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS base

WORKDIR /sourcecode
COPY ./src ./src/
COPY ./benchmarks ./benchmarks/
RUN ls -la /sourcecode/*

WORKDIR /sourcecode/benchmarks/ClusterBenchmark
RUN dotnet restore
RUN dotnet build -c Release -o /app

FROM base AS publish

RUN dotnet publish -c Release -o /app
FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "ClusterBenchmark.dll"]