<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
    <PropertyGroup Label="Configuration">
        <NoWarn>8981</NoWarn>
        <RootNamespace>Proto.Tests</RootNamespace>
        <LangVersion>10</LangVersion>
        <OutputType>Library</OutputType>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\Proto.Actor\Proto.Actor.csproj"/>
        <ProjectReference Include="..\Proto.TestFixtures\Proto.TestFixtures.csproj"/>
        <ProjectReference Include="..\..\src\Proto.TestKit\Proto.TestKit.csproj"/>
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
      <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework)' == 'net9.0' Or '$(TargetFramework)' == 'net10.0'">
        <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    </ItemGroup>
</Project>
