<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <NoWarn>8981</NoWarn>
        <IsPackable>true</IsPackable>
        <Nullable>enable</Nullable>
        <LangVersion>10</LangVersion>
        <TargetFrameworks>net8.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Proto.Cluster\Proto.Cluster.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="StackExchange.Redis" />
    </ItemGroup>

</Project>
