<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>10</LangVersion>
        <TargetFrameworks>net6.0;net7.0;net8.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable> 
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="dotnet-etcd" Version="7.2.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Proto.Actor\Proto.Actor.csproj" />
      <ProjectReference Include="..\Proto.Cluster\Proto.Cluster.csproj" />
    </ItemGroup>

</Project>
