<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">

    <PropertyGroup>
        <LangVersion>10</LangVersion>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable> 
    </PropertyGroup>

    <ItemGroup>

      <PackageReference Include="dotnet-etcd"  />

    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Proto.Actor\Proto.Actor.csproj" />
      <ProjectReference Include="..\Proto.Cluster\Proto.Cluster.csproj" />
    </ItemGroup>

</Project>
