<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <NoWarn>8981</NoWarn>
        <TargetFrameworks>net8.0</TargetFrameworks>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <LangVersion>10</LangVersion>
    </PropertyGroup>


    <ItemGroup>
        <ProjectReference Include="..\Proto.Cluster.Tests\Proto.Cluster.Tests.csproj" />
        <ProjectReference Include="..\Proto.TestFixtures\Proto.TestFixtures.csproj" />
        <ProjectReference Include="..\..\src\Proto.Actor\Proto.Actor.csproj" />
    </ItemGroup>

</Project>
