{
 "title": "Proto Actor sample dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cluster members",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(protocluster_members_count)"
    }
   ]
  },
  {
   "title": "Total virtual actors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum(protocluster_virtualactors) by (clusterkind)",
     "legendFormat": "{{clusterkind}}"
    }
   ]
  },
  {
   "title": "Threadpool latency 99p",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(protoactor_threadpool_latency_duration_seconds_bucket[$__rate_interval])) by(id, le))",
     "legendFormat": "system {{id}}"
    }
   ]
  },
  {
   "title": "Virtual actor request rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(protocluster_virtualactor_requestasync_duration_seconds_count[$__rate_interval])) by (clusterkind)",
     "legendFormat": "{{clusterkind}}"
    }
   ]
  },
  {
   "title": "Virtual actor request duration 95p",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(protocluster_virtualactor_requestasync_duration_seconds_bucket[$__rate_interval])) by (clusterkind, le))",
     "legendFormat": "req to: {{clusterkind}}"
    }
   ]
  },
  {
   "title": "Actor spawn rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "rate(protoactor_actor_spawn_count{}[$__interval])",
     "legendFormat": "{{actortype}}"
    }
   ]
  },
  {
   "title": "Virtual actor resolve PID rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(protocluster_resolve_pid_duration_seconds_count[$__rate_interval])) by (clusterkind)",
     "legendFormat": "{{clusterkind}}"
    }
   ]
  },
  {
   "title": "Virtual actor resolve PID duration 95p",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(protocluster_resolve_pid_duration_seconds_bucket[$__rate_interval])) by (clusterkind, le))",
     "legendFormat": "{{clusterkind}}"
    }
   ]
  },
  {
   "title": "Mailbox length",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "rate(protoactor_actor_mailbox_length_count{}[$__interval])",
     "legendFormat": "{{actortype}}"
    }
   ]
  },
  {
   "title": "Actor receive duration 95p",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(protoactor_actor_messagereceive_duration_seconds_bucket{}[$__rate_interval])) by (actortype, le))",
     "legendFormat": "{{actortype}}"
    }
   ]
  }
 ]
}