apiVersion: v1
kind: ServiceAccount
metadata:
  name: proto-cluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: proto-cluster
  labels:
    app: kubediag
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - pods
      - services
      - services/status
    verbs:
      - get
      - list
      - watch
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proto-cluster
  labels:
    app: kubediag
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: proto-cluster
subjects:
  - kind: ServiceAccount
    name: proto-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: testing
  labels:
    app: kubediag
spec:
  ports:
    - port: 8080
      name: protoactor
  selector:
    app: kubediag
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diagapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubediag
  template:
    metadata:
      labels:
        app: kubediag
        version: v1
    spec:
      serviceAccountName: proto-cluster
      containers:
        - name: kubediag
          # there is nothing sensitive in here, its just a diagnostics app
          image: rogeralsing/kubediag:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: "REDIS"
              value: "redis"
            - name: PROTOPORT
              value: "8080"
            - name: PROTOHOST
              value: "0.0.0.0"
            - name: "PROTOHOSTPUBLIC"
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
