<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>10</LangVersion>
        <Nullable>enable</Nullable>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Proto.Cluster\Proto.Cluster.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="StackExchange.Redis" />
    </ItemGroup>

</Project>
