<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>10</LangVersion>
        <TargetFrameworks>net8.0</TargetFrameworks>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Proto.Cluster\Proto.Cluster.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MongoDB.Driver" Version="2.26.0" />
      <PackageReference Include="Roslynator.Analyzers" Version="4.0.2">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Update="Microsoft.SourceLink.GitHub" Version="1.1.1" />
    </ItemGroup>

</Project>
