<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>10</LangVersion>
        <TargetFrameworks>net8.0</TargetFrameworks>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Proto.Cluster\Proto.Cluster.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MongoDB.Driver" />

    </ItemGroup>

</Project>
