<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>10</LangVersion>
    <TargetFrameworks>net8.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Divergic.Logging.Xunit" Version="4.0.0" />
    <PackageReference Include="Roslynator.Analyzers" Version="4.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Update="FluentAssertions" Version="6.12.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Proto.Remote\Proto.Remote.csproj" />
    <ProjectReference Include="..\Proto.Remote.Tests.Messages\Proto.Remote.Tests.Messages.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <DefineConstants>NETCORE</DefineConstants>
  </PropertyGroup>
</Project>
