<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <LangVersion>10</LangVersion>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Neovolve.Logging.Xunit" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\Proto.Remote\Proto.Remote.csproj" />
        <ProjectReference Include="..\Proto.Remote.Tests.Messages\Proto.Remote.Tests.Messages.csproj" />
        <ProjectReference Include="..\..\src\Proto.TestKit\Proto.TestKit.csproj" />
    </ItemGroup>
    <PropertyGroup>
        <!-- Ensure NETCORE is defined for the .NET 8 build -->
        <DefineConstants>$(DefineConstants);NETCORE</DefineConstants>
    </PropertyGroup>
</Project>
