<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
    <PropertyGroup>
        <NoWarn>8981</NoWarn>
        <RootNamespace>Proto</RootNamespace>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
        <LangVersion>10</LangVersion>
        <TargetFrameworks>net8.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Google.Protobuf" />
        <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="System.Collections.Immutable" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="System.Diagnostics.DiagnosticSource" />
        <PackageReference Include="System.Text.Json" />
        <PackageReference Include="System.Threading.Channels" />
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="Protos.proto" GrpcServices="Server" />
    </ItemGroup>
</Project>
