name: Build and test PRs

on: [pull_request]

env:
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
  TERM: xterm
  
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --entrypoint redis-server
      mongodb:
        image: mongo
        ports:
          - 27017/tcp

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "7.0.x"
          include-prerelease: true
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            6.0.x
            3.1.x

      - name: Build
        run: dotnet build ProtoActor.sln -c Release

  test-slow:  # slow tests that should run in parallel
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --entrypoint redis-server
    
    strategy:
      matrix:
        dotnet:
          - net7.0
          - net6.0
          - netcoreapp3.1
        test:
          - "tests/Proto.Cluster.Tests/*.csproj"
          - "tests/Proto.Cluster.PartitionIdentity.Tests/*.csproj"
          - "tests/Proto.Cluster.RedisIdentity.Tests/*.csproj"
          - "tests/Proto.Cluster.PubSub.Tests/*.csproj"
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "7.0.x"
          include-prerelease: true
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            6.0.x
            3.1.x

      - name: Run tests ${{ matrix.test }}
        timeout-minutes: 15
        env:
          ConnectionStrings__Redis: localhost:${{ job.services.redis.ports[6379] }},syncTimeout=10000
        run: |
          dotnet test ${{ matrix.test }} -c Release -f ${{ matrix.dotnet }} --logger GitHubActions
