name: Build and test PRs

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --entrypoint redis-server
      mongodb:
        image: mongo
        ports:
          - 27017/tcp

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.100"
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"

      - name: Build
        run: dotnet build ProtoActor.sln -c Release

  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --entrypoint redis-server
      mongodb:
        image: mongo
        ports:
          - 27017/tcp

    strategy:
      matrix:
        dotnet:
          - net5.0
          - netcoreapp3.1
        test:
          - "tests/Proto.Actor.Tests/*.csproj"
          - "tests/Proto.Remote.Tests/*.csproj"
          - "tests/Proto.Persistence.Tests/*.csproj"
          - "tests/Proto.Cluster.Tests/*.csproj"
          - "tests/Proto.Cluster.Identity.Tests/*.csproj"
          - "tests/Proto.Cluster.CodeGen.Tests/*.csproj"

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.100"
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x"

      - name: Run tests ${{ matrix.test }}
        timeout-minutes: 5
        env:
          ConnectionStrings__MongoDB: mongodb://localhost:${{ job.services.mongodb.ports[27017] }}/ProtoMongo
          ConnectionStrings__Redis: localhost:${{ job.services.redis.ports[6379] }},syncTimeout=10000
        run: |
          dotnet test ${{ matrix.test }} -c Release -f {{ matrix.dotnet }}
